import { Theme } from '@radix-ui/themes'
import './globals.css'
import "@radix-ui/themes/styles.css"
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import AppSidebar from '@/components/sidebar'

const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway', weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.variable}>
        <Theme accentColor='red' radius='large' className='font-raleway'>
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            {children}
          </SidebarProvider>
        </Theme>
      </body>
    </html>
  )
}
